name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          java-package: 'jdk'
          architecture: 'x64'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run tests using Maven
      - name: Run tests with Maven
        run: mvn test

      # Step 5: Optionally, deploy or package the application (if needed)
      - name: Package application
        run: mvn package

      # Optional: Run additional scripts or commands if needed
      - name: Additional step (optional)
        run: |
          echo "Add other actions to build, test, and deploy your project."
